#!/usr/bin/env python3
"""Generate tools/bundled_secrets.py with an encrypted DeepSeek API key."""

from __future__ import annotations

import argparse
import os
from pathlib import Path

try:
    from tools import model_explainer, secret_store
except ModuleNotFoundError:
    import model_explainer
    import secret_store


def read_key(explicit_key: str | None = None) -> str:
    if explicit_key:
        return explicit_key.strip()
    env_key = os.environ.get("DEEPSEEK_API_KEY")
    if env_key:
        return env_key.strip()
    config_key = model_explainer.load_local_config().get("deepseek_api_key")
    if isinstance(config_key, str) and config_key.strip():
        return config_key.strip()
    raise SystemExit("No DeepSeek API key found in --api-key, DEEPSEEK_API_KEY, or local settings.json")


def render_module(blob: str) -> str:
    return (
        "# Generated by tools/bundle_deepseek_key.py.\n"
        "# Contains an encrypted API key blob for portable test builds.\n"
        "DEEPSEEK_API_KEY_BLOB = (\n"
        f"    {blob!r}\n"
        ")\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Bundle encrypted DeepSeek API key for test distribution")
    parser.add_argument("--api-key", help="DeepSeek API key. Prefer env/config to avoid shell history.")
    parser.add_argument("--output", default="tools/bundled_secrets.py")
    args = parser.parse_args(argv)

    key = read_key(args.api_key)
    blob = secret_store.encrypt_secret(key)
    Path(args.output).write_text(render_module(blob), encoding="utf-8")
    print(f"Wrote encrypted key blob to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
