# Generated by tools/bundle_deepseek_key.py.
# Contains an encrypted API key blob for portable test builds.
DEEPSEEK_API_KEY_BLOB = (
    'eyJ2IjoxLCJzYWx0IjoiZHYwWW5QMXdkUlNRdDdQaGZTY1J0UT09IiwiY2lwaGVydGV4dCI6IlpQbU9fZ1M4Zk9XUFhHSmdWLVFDQmptSEJVYjJVOEVpNG1TTDl4NW54TjRlTWxnPSIsInRhZyI6IjA4TFQwLURteXlvWW1tcVljX2czV0VRRllvOGN3TnYxdWJyWGhmN1Y3TlU9In0='
)
